language: csharp
solution: Core6502DotNet.sln
install:
  - nuget restore Core6502DotNet.sln
  - nuget install Nunit.Runners -Version 3.6.1.0 -OutputDirectory testrunner
script:
  - msbuild Core6502DotNet.sln /t:Build /p:Configuration=Release
  - mono ./Core6502DotNet.Net/bin/Release/netcoreapp3.1/6502.Net.exe --version
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./NUnit.Tests/bin/Release/NUnit.Tests.dll
